image: python:3.7

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -e '.[all]'
  - pip install pytest pytest-cov

stages:
  - Test

pytest:
  stage: Test
  tags:
  - public-docker
  script:
    - coverage run -m pytest --log-cli-level=INFO
    - coverage report
    - coverage xml
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/cobertura.xml

