default:
  image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_DIR: "${CI_PROJECT_DIR}/.cache/pre-commit"
  VENV_DIR: "${CI_PROJECT_DIR}/venv"

cache:
  paths:
    - ${PIP_CACHE_DIR}
    - ${PRE_COMMIT_DIR}
    - ${VENV_DIR}${PY_VER}

.install_dependencies:
  before_script:
    - pip install virtualenv
    - virtualenv venv_"${PYTHON_VERSION}"
    - source venv_"${PYTHON_VERSION}"/bin/activate
    - python -V
    - pip install -U setuptools
    - pip install -e '.[all]'
    - pip install pytest pytest-cov pytest-xdist

.pages_dependencies:
  before_script:
    - pip install virtualenv
    - virtualenv venv_3.9
    - source venv_3.9/bin/activate
    - python -V
    - pip install mkdocs mkdocs-material mkdocs-autorefs mkdocs-git-revision-date-localized-plugin mkdocs-material \
                  mkdocs-material-extensions mkdocs-pdf-export-plugin mkdocs-with-pdf mkdocstrings mkdocstrings-python \
                  mkgendocs mkpdfs-mkdocs black

stages:
  - test
  - deploy

py39:pytest:
  variables:
    PYTHON_VERSION: "3.9"
  image: python:3.9
  stage: test
  extends: .install_dependencies
  tags:
  - public-docker
  script:
    - pytest -n 4 --log-cli-level=INFO --cov=speadi tests/
    - coverage xml -o tests/coverage.xml
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: tests/coverage.xml

various:pytest:
  parallel:
    matrix:
      - PYTHON_VERSION: ['3.7', '3.8', '3.10']
  image: python:${PYTHON_VERSION}
  stage: test
  extends: .install_dependencies
  tags:
  - public-docker
  script:
    - pytest --log-cli-level=INFO --cov=speadi tests/
    - coverage xml -o tests/"${PYTHON_VERSION}"_coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: tests/"${PYTHON_VERSION}"_coverage.xml

doc site test:
  stage: test
  extends: .pages_dependencies
  tags:
  - public-docker
  script:
  - mkdocs build --strict --verbose --site-dir site_test
  artifacts:
    paths:
    - site_test

pages:
  stage: deploy
  extends: .pages_dependencies
  needs:
    - py39:pytest
    - doc site test
  tags:
  - public-docker
  script:
  - mkdocs build --strict --verbose --site-dir public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
