image: python:3.7

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -e '.[opt]'
  - pip install pytest

stages:
  - Test

test_grt:
  stage: Test
  tags:
  - public-docker
  script:
    - pytest tests/test_grt.py

test_Grt:
  stage: Test
  tags:
  - public-docker
  script:
    - pytest tests/test_Grt.py
