site_name: SPEADI: Scalable Protein Environment Analysis for Dynamics and Ions
repo_url: https://github.com/FZJ-JSC/speadi
repo_name: SPEADI

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.follow
  icon:
    repo: fontawesome/brands/github

nav:
  - Documentation:
      - Introduction: index.md
      - Time-Resolved Radial Distribution Functions (TRRDFs): TRRDFs.md
      - van Hove Dynamic Correlation Functions (VHFs): vanhove.md
      - Additional helper functions: helpers.md
  - Examples:
      - Examples 1: examples.md
  - Citation:
      - How to cite: citation.md
      - References: references.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_full_path: False
            show_root_toc_entry: False
            line_length: 60
            docstring_section_style: spacy
  - git-revision-date-localized:
      enable_creation_date: true
  - pdf-export:
      verbose: True
      media_type: print
      combined: True
      combined_output_path: docs/documentation.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
# - with-pdf:
#     output_path: docs/user_guide.pdf

# extra:
#   version:
#     provider: mike

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.highlight:
        anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; SPEADI 2022 Forschungszentrum Jülich, Jülich Supercomputing Centre