#+title: Time-resolved RDF.py
#+author: Emile de Bruyn
#+export_file_name: ../README.md

* Time-resolved RDF.py
  This package provides an optimised function to calculate Time-resolved Radial Distribution Functions using atomistic simulation trajectory data.

  Trajectory data may be anything that the package ~MDTraj~ can handle, or preferably a string pointing to the location of such data.
 
** Explanation 
   [[file:docs/trrdf_averaging.svg]]
  
** Install
   Installation is provided easily through ~pip~. It can be installed either directly as a package, or as an editable source.
  
*** Direct installation
    For installation into the default python environment, run the following in a terminal:
    #+begin_src bash
		 pip install git+https://gitlab.version.fz-juelich.de/debruyn1/emiles-phd-project.git#egg=version_subpkg\&subdirectory=scripts/vanhove
    #+end_src
    To install for just the current user, add the ~--user~ option:
    #+begin_src bash
		 pip install --user git+https://gitlab.version.fz-juelich.de/debruyn1/emiles-phd-project.git#egg=version_subpkg\&subdirectory=scripts/vanhove
    #+end_src

*** Editable source installation
    Open up a terminal. Navigate to the location you want to clone this repository. Then, run the following to clone the whole repository:
    #+begin_src bash
		 git clone ssh://git@gitlab.version.fz-juelich.de:10022/debruyn1/emiles-phd-project.git
    #+end_src
    Then, install locally using ~pip~ (after entering the package sub-directory):
	  #+begin_src bash
		 cd emiles-phd-project/scripts/time_resolved_rdf/ && pip install -e .
    #+end_src

** [WIP] Citation
   
** Contributors
   - Emile de Bruyn

** [WIP] License
